package consts

const (
	Collection_Json    string = "authentication"
	UserType_Json      string = "ECOMMERCE_USER"
	SqliteDatabase     string = "driversNektria"
	TestFileRoute      string = "./test/files"
	ReadFileRoute      string = "./filesToRead"
	FilesRoute         string = "./files"
	FilesSQL           string = "sql"
	FilesShopsSQL      string = "sqlShops"
	FilesNames         string = "names"
	FilesCsv           string = "usersAndPasswords"
	FilesJson          string = "userCouchbase"
	FilesAclJson       string = "usersEndPoint"
	FilesUserListJson  string = "userList"
	FilesAclSql        string = "aclSql"
	FilesExpedition    string = "expeditionSql"
	FilesPicking       string = "pickingSql"
	FilesSorterMap     string = "sorterMap"
	LogsRoute          string = "./logs/logs.log"
	LogsTestRoute      string = "../../logs/logs_test.log"
	GenericDriverEmail string = "driver@gmail.com"
	AuthEndpointUrl    string = "https://internal.pro.es.ecom.dgrp.io/api/v1/auth/user"
	AclEndpointUrl     string = "https://com.pro.api.dgrp.io/v1/acl/users/%v/roles-segmentations-applications"
	UserListFileName   string = "userList"
)
