package consts

const (
	PACLocationQuerys = "INSERT INTO wms.location_picking (warehouse_code,location,type,location_zone,location_format,location_template,corridor,module,shelf,gap,template,picking_sequence,picking_zone,rotation,weight,height,width,length,capacity_fee,restocking_fee,blocked,active,direction,putaway_sequence,cycle_count) VALUES ('%v','98.98.98.98','Picking','AMB','Unidades','BAJAS','98','98','98','98','A',9999999,'A','R',10000.0,10000.0,10000.0,10000.0,80.0,80.0,false,true,'1',1,false);\n" +
		"INSERT INTO wms.location_intermediate (warehouse_code,location,type,location_zone,location_template,area,position,template_area,active) VALUES ('%v','PAC.000','Picking','AMB','PAC.000','00','00','PAC',true);\n" +
		"INSERT INTO wms.location_picking (warehouse_code,location,type,location_zone,location_format,location_template,corridor,module,shelf,gap,template,picking_sequence,picking_zone,rotation,weight,height,width,length,capacity_fee,restocking_fee,blocked,active,direction,putaway_sequence,cycle_count) VALUES ('%v','99.99.99.99','Picking','AMB','Unidades','DESCONOCIDO','99','99','99','99','A',6666666,'A','R',10000.0,10000.0,10000.0,10000.0,80.0,80.0,false,true,'1',1,false);\n" +
		"INSERT INTO wms.location_picking ( warehouse_code,type,location_format,template,corridor,module,shelf,gap,location_zone,picking_zone,weight,height,width,length,capacity_fee,restocking_fee,picking_sequence,putaway_sequence,direction,blocked,active,rotation,cycle_count,location_template,location) VALUES ('%v'::character varying,'Picking'::character varying,'Unidades'::character varying,'P'::character varying,'77'::character varying,'77'::character varying,'77'::character varying,'77'::character varying,'PAN'::character varying,'PAN'::character varying,'250000'::real,'40'::real,'60'::real,'100'::real,'80'::real,'20'::real,'7777777'::integer,'1506'::integer,'ASC'::character varying,'false'::boolean,'true'::boolean,'A'::character varying,'false'::boolean,'P.77.77.77.77'::character varying,'77.77.77.77'::character varying) ON CONFLICT ON CONSTRAINT location_picking_pkey DO UPDATE SET warehouse_code = EXCLUDED.warehouse_code,type = EXCLUDED.type,location_format = EXCLUDED.location_format,template = EXCLUDED.template,corridor = EXCLUDED.corridor,module = EXCLUDED.module,shelf = EXCLUDED.shelf,gap = EXCLUDED.gap,location_zone = EXCLUDED.location_zone,picking_zone = EXCLUDED.picking_zone,weight = EXCLUDED.weight,height = EXCLUDED.height,width = EXCLUDED.width,length = EXCLUDED.length,capacity_fee = EXCLUDED.capacity_fee,restocking_fee = EXCLUDED.restocking_fee,picking_sequence = EXCLUDED.picking_sequence,putaway_sequence = EXCLUDED.putaway_sequence,direction = EXCLUDED.direction,blocked = EXCLUDED.blocked,active = EXCLUDED.active,rotation = EXCLUDED.rotation,cycle_count = EXCLUDED.cycle_count,location_template = EXCLUDED.location_template,location = EXCLUDED.location;\n" +
		"INSERT INTO wms.location_picking ( warehouse_code,type,location_format,template,corridor,module,shelf,gap,location_zone,picking_zone,weight,height,width,length,capacity_fee,restocking_fee,picking_sequence,putaway_sequence,direction,blocked,active,rotation,cycle_count,location_template,location) VALUES ('%v'::character varying,'Picking'::character varying,'Unidades'::character varying,'P'::character varying,'88'::character varying,'88'::character varying,'88'::character varying,'88'::character varying,'PAN'::character varying,'PAN'::character varying,'250000'::real,'40'::real,'60'::real,'100'::real,'80'::real,'20'::real,'88888888'::integer,'1507'::integer,'ASC'::character varying,'false'::boolean,'true'::boolean,'A'::character varying,'false'::boolean,'P.88.88.88.88'::character varying,'88.88.88.88'::character varying) ON CONFLICT ON CONSTRAINT location_picking_pkey DO UPDATE SET warehouse_code = EXCLUDED.warehouse_code,type = EXCLUDED.type,location_format = EXCLUDED.location_format,template = EXCLUDED.template,corridor = EXCLUDED.corridor,module = EXCLUDED.module,shelf = EXCLUDED.shelf,gap = EXCLUDED.gap,location_zone = EXCLUDED.location_zone,picking_zone = EXCLUDED.picking_zone,weight = EXCLUDED.weight,height = EXCLUDED.height,width = EXCLUDED.width,length = EXCLUDED.length,capacity_fee = EXCLUDED.capacity_fee,restocking_fee = EXCLUDED.restocking_fee,picking_sequence = EXCLUDED.picking_sequence,putaway_sequence = EXCLUDED.putaway_sequence,direction = EXCLUDED.direction,blocked = EXCLUDED.blocked,active = EXCLUDED.active,rotation = EXCLUDED.rotation,cycle_count = EXCLUDED.cycle_count,location_template = EXCLUDED.location_template,location = EXCLUDED.location;\n" +
		"UPDATE wms.location_picking SET active = true WHERE active = false and warehouse_code = '%v'"
)
